# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-fd0d1770-8034-4446-9e80-4e317281227a";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-fd0d1770-8034-4446-9e80-4e317281227a".device = "/dev/disk/by-uuid/fd0d1770-8034-4446-9e80-4e317281227a";

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-fd0d1770-8034-4446-9e80-4e317281227a";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/luks-fd0d1770-8034-4446-9e80-4e317281227a";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/608B-2D00";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # swapDevices =
    # [ { device = "/dev/mapper/luks-f62e5170-88df-4d7a-8c18-966cb8074668"; }
    # ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
